import glob
import os.path
import pandas
import pygplates


#########################################################################
# Script to extract the optimized 005-000 rotations, from the output    #
# of the optimization workflow, and insert them into the original       #
# rotation files such that a 005-000 sequence is not required.          #
#########################################################################

optimised_model_name = None
#optimised_model_name = 'optAPM_r1228'

# If model name not manually specified above then read it from the main 'Optimised_APM' module.
if not optimised_model_name:
    import Optimised_APM  # To get 'model_name'
    optimised_model_name = Optimised_APM.model_name

# In some cases the original rotation files already have a 005-000 sequence.
# Presumably because they are the output of an old version of the
# optimization workflow that did not remove 005-000 from its output.
# Note: the new workflow introduces 005-000 only during the optimization workflow, and this
# script is supposed to remove it after the workflow has run.
#
# So we have the option to remove 005-000 and set all fixed plate ids that are 005 back to 000.
# It's an option because the owner of the original rotation files might want to keep 005-000 for some reason.
remove_005_000_from_original_rotations = True

# The main data directory is the directory containing this source file.
base_dir = os.path.abspath(os.path.dirname(__file__))

# Directory containing the original rotation files.
original_rotation_data_dir = os.path.join(base_dir, 'data', 'Global_Model_WD_Internal_Release_2016_v3')

# Directory containing the optimised rotation files.
optimised_rotation_data_dir = os.path.join(original_rotation_data_dir, 'optimisation')

# The combined optimised rotation file generated by the optimisation workflow.
optimised_rotation_filename = os.path.join(
    optimised_rotation_data_dir,
    'all_rotations_{0}.rot'.format(optimised_model_name))

# Gather all the original '.rot' files (these are our output files).
original_rotation_filenames = glob.glob(os.path.join(original_rotation_data_dir, '*.rot'))


# Read original rotation files.
original_rotation_feature_collections = [pygplates.FeatureCollection(filename)
        for filename in original_rotation_filenames]

# The original rotation model before we modify it below.
original_rotation_model = pygplates.RotationModel(original_rotation_feature_collections)


print "Extracting optimized rotations from model: %s" % optimised_model_name

# Read optimized rotation file.
optimised_rotation_features = pygplates.FeatureCollection(optimised_rotation_filename)


# Extract the 005-000 sequence so we can access the times of its rotation samples.
# We'll also use the 005-000 sequence to build a RotationModel to extract those rotations.
# We only need a rotation model to extract the optimized 005-000 rotations (ignoring everything else).
# Note that the optimisation workflow currently generates only a single 005-000 sequence.
absolute_plate_motion_rotation_feature = None
absolute_plate_motion_rotation_sample_times = None
for rotation_feature in optimised_rotation_features:
    total_reconstruction_pole = rotation_feature.get_total_reconstruction_pole()
    if total_reconstruction_pole:
        fixed_plate_id, moving_plate_id, rotation_sequence = total_reconstruction_pole
        if fixed_plate_id == 0 and moving_plate_id == 5:
            if absolute_plate_motion_rotation_feature:
                raise ValueError('Expected a single 005-000 sequence, but got multiple, in output rotation file of optimisation workflow')
            absolute_plate_motion_rotation_feature = rotation_feature
            absolute_plate_motion_rotation_sample_times = [pygplates.GeoTimeInstant(sample.get_time())
                for sample in rotation_sequence.get_enabled_time_samples()]

if absolute_plate_motion_rotation_feature is None:
    raise ValueError('Expected a single 005-000 sequence, but got none, in output rotation file of optimisation workflow')

absolute_plate_motion_rotation_model = pygplates.RotationModel(absolute_plate_motion_rotation_feature)

COMMENT_OPTIMISED_ABSOLUTE_PLATE_MOTION = 'Adjusted to include optimized absolute plate motion'

# For any rotation features referencing fixed plate 005, merge the optimised 005-000 sequence into it and have it reference 000.
for rotation_feature_collection_index, rotation_feature_collection in enumerate(original_rotation_feature_collections):
    modified_rotation_feature_collection = False
    
    if remove_005_000_from_original_rotations:
        rotation_features_minus_005_000 = []
    
    for rotation_feature in rotation_feature_collection:
        total_reconstruction_pole = rotation_feature.get_total_reconstruction_pole()
        if total_reconstruction_pole:
            fixed_plate_id, moving_plate_id, rotation_sequence = total_reconstruction_pole
            # If the current rotation feature references plate 000 then we need to adjust using the
            # optimized absolute rotations (005-000).
            # We also include plate 5 if we're removing 005-000 (since we'll need to change it to 000).
            if (fixed_plate_id == 0 or (remove_005_000_from_original_rotations and fixed_plate_id == 5)) and moving_plate_id != 999:
                rotation_samples = rotation_sequence.get_enabled_time_samples()
                
                # For the current rotation samples prefix their comments to notify rotation has been
                # adjusted to include the optimized absolute plate motion.
                for rotation_sample in rotation_samples:
                    description = rotation_sample.get_description()
                    if description is None:
                        # No description yet. Just use the optimised absolute plate motion comment.
                        new_description = COMMENT_OPTIMISED_ABSOLUTE_PLATE_MOTION
                    elif description.lstrip().startswith(COMMENT_OPTIMISED_ABSOLUTE_PLATE_MOTION):
                        # Description already has the optimised absolute plate motion prefix.
                        new_description = description
                    else:
                        # First time prefixing description.
                        new_description = COMMENT_OPTIMISED_ABSOLUTE_PLATE_MOTION + ': ' + description
                    rotation_sample.set_description(new_description)
                
                # Record the current sample times (as GeoTimeInstant so we can compare them within an epsilon).
                rotation_sample_times = [pygplates.GeoTimeInstant(sample.get_time()) for sample in rotation_samples]
                min_rotation_sample_time, max_rotation_sample_time = rotation_sample_times[0], rotation_sample_times[-1]
                
                # Add in new samples corresponding to sample times of 005-000 that do not coincide with the current sequence.
                # We don't want to generate duplicate samples (ie, with the same time).
                # Also don't add sample times outside the time range of the current rotation samples.
                new_rotation_samples = list(rotation_samples)
                for absolute_plate_motion_sample_time in absolute_plate_motion_rotation_sample_times:
                    if (absolute_plate_motion_sample_time not in rotation_sample_times and
                        absolute_plate_motion_sample_time >= min_rotation_sample_time and
                        absolute_plate_motion_sample_time <= max_rotation_sample_time):
                        interpolated_original_rotation = original_rotation_model.get_rotation(
                            absolute_plate_motion_sample_time,
                            moving_plate_id,
                            # Note that we're using 'fixed_plate_id' here and not '0'.
                            # This is because if fixed_plate_id==5 and we're removing 005-000 then
                            # we're going to be adding the optimized 005-000 to this later...
                            fixed_plate_id=fixed_plate_id)
                        interpolated_rotation_sample = pygplates.GpmlTimeSample(
                            # Note that we'll add in the optimized absolute rotation later...
                            pygplates.GpmlFiniteRotation(interpolated_original_rotation),
                            absolute_plate_motion_sample_time,
                            COMMENT_OPTIMISED_ABSOLUTE_PLATE_MOTION)
                        new_rotation_samples.append(interpolated_rotation_sample)
                
                # Need to re-sort the rotation samples because we essentially merged two sequences.
                new_rotation_samples.sort(key = lambda sample: sample.get_time())
                
                # Add in the optimized absolute rotations (005-000).
                for rotation_sample in new_rotation_samples:
                    # Extract the 005-000 absolute rotation at the current sample time.
                    absolute_plate_motion_rotation = absolute_plate_motion_rotation_model.get_rotation(
                        rotation_sample.get_time(),
                        5,
                        fixed_plate_id=0)
                    
                    if moving_plate_id == 5:
                        # The original rotation file already had a 005-000 sequence.
                        # Presumably because it used the output of an old version of the
                        # optimization workflow that did not remove 005-000 from its output.
                        # Here we just swap the old 005-000 with the new 005-000.
                        rotation = absolute_plate_motion_rotation
                    elif fixed_plate_id == 5:
                        rotation = rotation_sample.get_value().get_finite_rotation()
                        if remove_005_000_from_original_rotations:
                            rotation = absolute_plate_motion_rotation * rotation
                    else:
                        # Our sequence now references fixed plate 000 instead of 005 so we need to adjust its rotations.
                        #
                        #   R_opt(0->t,000->005) * R(0->t,000->moving) -> R(0->t,000->moving)
                        #
                        rotation = rotation_sample.get_value().get_finite_rotation()
                        rotation = absolute_plate_motion_rotation * rotation
                    
                    rotation_sample.get_value().set_finite_rotation(rotation)
                
                # Store the new sequence of samples in the current rotation feature.
                rotation_feature.set_total_reconstruction_pole(
                    0,
                    moving_plate_id,
                    pygplates.GpmlIrregularSampling(new_rotation_samples))
                
                # Mark the rotation feature's collection as modified (so we can later write it out to disk).
                modified_rotation_feature_collection = True
            
            if remove_005_000_from_original_rotations:
                # Keep all rotation features except 005-000.
                if not (fixed_plate_id == 0 and moving_plate_id == 5):
                    rotation_features_minus_005_000.append(rotation_feature)
                else:
                    # Mark the rotation feature's collection as modified (so we can later write it out to disk).
                    # It's modified because we're removing 005-000.
                    modified_rotation_feature_collection = True
    
    if remove_005_000_from_original_rotations and modified_rotation_feature_collection:
        rotation_feature_collection = pygplates.FeatureCollection(rotation_features_minus_005_000)
    
    # Write a modified version of the current original rotation feature collection to disk.
    if modified_rotation_feature_collection:
        # Each output filename is the input filename with a 'optAPM' appended (before the extension).
        input_rotation_filename = original_rotation_filenames[rotation_feature_collection_index]
        base_filename, filename_ext = os.path.splitext(os.path.basename(input_rotation_filename))
        filename_root = os.path.join(optimised_rotation_data_dir, base_filename)
        output_rotation_filename = ''.join((filename_root, '_', optimised_model_name, filename_ext))
        
        print "Writing: %s" % os.path.basename(output_rotation_filename)
        
        rotation_feature_collection.write(output_rotation_filename)
