#!/bin/bash
#PBS -N mpi4py-python-2.7.9-openmpi-gcc
#PBS -P BGH
#PBS -l select=5:ncpus=4:mem=4Gb:mpiprocs=4,walltime=2:00:00

module load glew
module load proj
module load gdal
module load qt/4.8.6
module load qwt/6.1.3
module load cgal
module load boost
module load python
module load gmp/5.1.3
module load openmpi-gcc

cd $PBS_O_WORKDIR
export PYTHONPATH=$PYTHONPATH:/home/jscannon/gplates/builds/latest/python-api-2013-jul-25-build/bin

mpirun -np 20 python Optimised_APM.py
